### ISSUE TITLE
select file type based on header, not filename extension

### ISSUE THREAD

**Issue by andersvi** [openmusic-project/omaudiolib#2]
attempting to play a RIFF soundfile with the wrong filename extension - e.g. '.aiff' - results in silence

**Comment by j-bresson** [comment]
https://github.com/openmusic-project/omaudiolib/blob/e6f4224d61f8cd58eb7e21f543db1b89ee1551bb/Source/OMAudioFileReader.cpp#L35-L36

**Comment by andersvi** [comment]
https://github.com/openmusic-project/omaudiolib/blob/e6f4224d61f8cd58eb7e21f543db1b89ee1551bb/JuceLibraryCode/modules/juce_audio_formats/format/juce_AudioFormatManager.cpp#L136
has a method for instances of InputStream, perhaps it's useful in this context?

**Comment by andersvi** [comment]
Seems the approach [here](https://github.com/openmusic-project/omaudiolib/commit/a876b686cecd205169f2210ae4943fb93fb2e54b) solves the problem.

**Comment by andersvi** [comment]
Fixed in commit [a876b68](https://github.com/openmusic-project/omaudiolib/commit/a876b686cecd205169f2210ae4943fb93fb2e54b) - using instances of ***InputStream*** instead of ***File***.

Branch test_input_stream rebased into master.
